### ISSUE TITLE
Implement gem `cn-ccs` as counterpart to `iso-ics`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/cnccs#1]
Just like `iso-ics`, implement this gem to read https://github.com/riboseinc/cn-ccs-codes.

**Comment by andrew2net** [comment]
@ronaldtse What methods should be implemented in the gem?

**Comment by ronaldtse** [comment]
@andrew2net now updated README.

**Comment by andrew2net** [comment]
@ronaldtse can't push to the cnccs repo
```
fatal: unable to access 'https://github.com/riboseinc/cnccs.git/': The requested URL returned error: 403
```

**Comment by ronaldtse** [comment]
@andrew2net sorry, fixed now 👍

**Comment by andrew2net** [comment]
@ronaldtse pushed and published the gem

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by ronaldtse** [comment]
Should we close this issue now?
